- app/controllers/application_controller.rb
- app/views/devise/confirmations/new.html.erb
- app/views/devise/mailer/confirmation_instructions.html.erb
- app/views/devise/mailer/email_changed.html.erb
- app/views/devise/mailer/password_change.html.erb
- app/views/devise/mailer/reset_password_instructions.html.erb
- app/views/devise/mailer/unlock_instructions.html.erb
- app/views/devise/passwords/edit.html.erb
- app/views/devise/passwords/new.html.erb
- app/views/devise/registrations/edit.html.erb
- app/views/devise/registrations/new.html.erb
- app/views/devise/sessions/new.html.erb
- app/views/devise/shared/_error_messages.html.erb
- app/views/devise/shared/_links.html.erb
- app/views/devise/unlocks/new.html.erb
- db/migrate/20200518103536_add_info_to_users.rb
- db/schema.rb
added user strong params, devise views and migration file
> Added User Registration

- app/assets/stylesheets/components/_navbar.scss
- app/views/layouts/application.html.erb
@yusuke0127 I added navbar to the application.html. Please check!
> Added navbar to the applicatio.html.erb

- Gemfile
- Gemfile.lock
- db/seeds.rb
Added the faker gem and seeded the db
> Add faker gem and seed the db

- app/views/pages/home.html.erb
added banner image to home page
> Added Banner to Home page

- app/assets/stylesheets/pages/_home.scss
> Added CSS to banner homepage

- config/routes.rb
> Added index routes for babysitter

- app/controllers/babysitters_controller.rb
- app/views/babysitters/index.html.erb
- test/controllers/babysitters_controller_test.rb
> Added controller with index method, & babysitter index view

- db/seeds.rb
Added the babysitter! @Katsulincon @pins-thoo
> Add babysitter seeds

- app/views/babysitters/index.html.erb
> Babysitter Index View List

- app/assets/stylesheets/components/_card.scss
- app/assets/stylesheets/components/_index.scss
- app/controllers/pages_controller.rb
- app/views/pages/home.html.erb
- app/views/pages/uidisplay.html.erb
- app/views/shared/_card.html.erb
- config/routes.rb
You can see component in http://localhost:3000/ui !
> Created card component

- app/controllers/reservations_controller.rb
- app/views/layouts/application.html.erb
- app/views/reservations/index.html.erb
- config/routes.rb
- test/controllers/reservations_controller_test.rb
@yusuke0127 @Katsulincon check :)
> Added Reservation Controller, Show View

- db/seeds.rb
Fixing seed file @pins-thoo @Katsulincon
> Add seed to reservation and fix some seeding attributes

- app/controllers/reservations_controller.rb
- app/views/reservations/index_babysitter.html.erb
- config/routes.rb
> No reservation yet...but it is working for now

- app/views/reservations/index.html.erb
- app/views/reservations/index_babysitter.html.erb
> Updated reservation views

- app/assets/stylesheets/components/_index.scss
- app/assets/stylesheets/components/_search_form.scss
- app/controllers/pages_controller.rb
- app/views/pages/uidisplay.html.erb
- app/views/shared/_home_search_bar.html.erb
Please check search bar component
> Created search bar component

- Gemfile
- Gemfile.lock
- app/controllers/application_controller.rb
- app/controllers/babysitters_controller.rb
- app/controllers/reservations_controller.rb
- app/policies/application_policy.rb
- app/policies/babysitter_policy.rb
- app/policies/reservation_policy.rb
- test/policies/babysitter_policy_test.rb
- test/policies/reservation_policy_test.rb
Added authorization please check @Katsulincon @pins-thoo
> Add pundit gem and implement authorization

- app/controllers/babysitters_controller.rb
- app/controllers/reservations_controller.rb
- app/models/babysitter.rb
- app/models/reservation.rb
- app/models/user.rb
- app/views/babysitters/show.html.erb
- app/views/reservations/index_babysitter.html.erb
- app/views/shared/_reservation_form.html.erb
- config/routes.rb
> Working reservation

- app/controllers/reservations_controller.rb
- app/policies/reservation_policy.rb
authorize creating of reservation @pins-thoo @Katsulincon
> Authorize create reservation for users

- app/assets/stylesheets/components/_index.scss
- app/assets/stylesheets/components/_tabs.scss
- app/views/reservations/index.html.erb
Please check tabs on reservations page
> Created tabs on reservations page

- app/models/reservation.rb
- app/views/babysitters/show.html.erb
- app/views/layouts/application.html.erb
- app/views/shared/_reservation_form.html.erb
> Updated working form

- app/assets/stylesheets/components/_babysitter_show_card.scss
- app/assets/stylesheets/components/_index.scss
- app/views/babysitters/show.html.erb
Please check babysitter show/reserve page.
> Styled babysitter show page

- app/controllers/reservations_controller.rb
- app/views/reservations/index.html.erb
Fixed the controller and the filter for the booking. Check please @Katsulincon @pins-thoo
> Fix the controller #create action and add filter to the bookings

- app/assets/stylesheets/components/_search_form.scss
- app/views/layouts/application.html.erb
- app/views/pages/home.html.erb
> Homepage search view updated

- app/assets/stylesheets/components/_card.scss
- app/views/babysitters/index.html.erb
> Changed the name color of babysitters cards

- app/views/reservations/index.html.erb
check please @Katsulincon @pins-thoo
> Fix styling for the booking list

- app/assets/stylesheets/components/_navbar.scss
- app/assets/stylesheets/config/_fonts.scss
> font updated

- app/views/layouts/application.html.erb
> Add sign out feature

- app/assets/stylesheets/components/_card.scss
- app/views/reservations/index.html.erb
> Added cards to reservations page

- app/assets/stylesheets/components/_tabs.scss
- app/views/reservations/index.html.erb
> Added default to tab

- app/assets/stylesheets/components/_card.scss
- app/views/reservations/index.html.erb
> Made text bigger and increased margin

- app/assets/stylesheets/components/_card.scss
- app/views/babysitters/index.html.erb
- app/views/babysitters/show.html.erb
- db/migrate/20200520021122_add_image_to_users.rb
- db/schema.rb
- db/seeds.rb
Added photo to the seed and it will now show the photo in the cards @pins-thoo @Katsulincon
> Add photo to the seed

- app/views/reservations/index.html.erb
> Changed the image of reservations card

- app/views/pages/home.html.erb
> added slogan to home page

- db/seeds.rb
> Remove pending from the status and katsu as a babysitter

- db/seeds.rb
edited the seeds check please! @pins-thoo @Katsulincon
> Remove katsu as a babysitter and added some other people

- app/views/pages/home.html.erb
- app/views/shared/_pages_search_bar.html.erb
- app/views/shared/_reservation_form.html.erb
> calender added

- app/controllers/babysitters_controller.rb
- app/controllers/pages_controller.rb
@Katsulincon @pins-thoo check please
> Make homepage viewable even without signing in

- app/controllers/pages_controller.rb
- app/controllers/users_controller.rb
- app/policies/user_policy.rb
- app/views/layouts/application.html.erb
- app/views/users/show.html.erb
- config/routes.rb
- test/controllers/users_controller_test.rb
- test/policies/user_policy_test.rb
Created the user controller and the show page for the controller. Please check @Katsulincon @pins-thoo
> Create controller for user and edited the navbar

- app/assets/stylesheets/components/_babysitter_show_card.scss
- app/views/babysitters/show.html.erb
> Changed card styling of babysitter show page

- app/controllers/babysitters_controller.rb
- app/controllers/users_controller.rb
- app/policies/babysitter_policy.rb
- app/policies/user_policy.rb
- app/views/devise/registrations/edit.html.erb
- config/routes.rb
> create a button to become a babysitter

- app/assets/stylesheets/components/_card.scss
- app/assets/stylesheets/pages/_index.scss
- app/views/babysitters/index.html.erb
> Changed the display of cards

- app/assets/stylesheets/pages/_index.scss
- app/assets/stylesheets/pages/_profile.scss
- app/views/users/show.html.erb
Button and link just goes to root_path at this moment!
@yusuke0127 @pins-thoo
> Styled user profile page

- app/views/babysitters/index.html.erb
> Fixed margin and replaced emoji

- app/assets/stylesheets/components/_babysitter_show_card.scss
- app/views/babysitters/show.html.erb
> Fixed the position of card and button

- app/controllers/babysitters_controller.rb
- app/controllers/users_controller.rb
- app/policies/babysitter_policy.rb
- app/views/babysitters/new.html.erb
- app/views/devise/registrations/edit.html.erb
- app/views/layouts/application.html.erb
- app/views/users/show.html.erb
- config/routes.rb
> Fix user update page

- app/assets/stylesheets/components/_become_babysitter_form.scss
- app/assets/stylesheets/components/_index.scss
- app/views/babysitters/new.html.erb
> Styled the form

- app/views/layouts/application.html.erb
check please @Katsulincon @pins-thoo
> Remove avatar photo when not signed in

- app/views/layouts/application.html.erb
check please @pins-thoo @Katsulincon
> Fix bugs when signing in and out

- app/javascript/packs/application.js
- app/javascript/plugins/flatpickr.js
> updated calendar without hard refresh

- app/controllers/reservations_controller.rb
- app/views/layouts/application.html.erb
- app/views/shared/_flashes.html.erb
Added alerts. please check @pins-thoo
> Added alerts when logging in and when making a reservation

- app/assets/stylesheets/components/_tabs.scss
- app/views/users/show.html.erb
check please @pins-thoo @Katsulincon
> Hide the be a babysitter button

- app/controllers/users_controller.rb
- app/policies/user_policy.rb
- app/views/reservations/_babysitter_card.html.erb
> profile directory working

- app/javascript/controllers/hello_controller.js
- app/javascript/controllers/index.js
- app/javascript/controllers/price_controller.js
- app/javascript/packs/application.js
- app/views/shared/_reservation_form.html.erb
- package.json
- yarn.lock
> Implement autocalcutation

- app/views/shared/_reservation_form.html.erb
> Changed the price description

- app/policies/babysitter_policy.rb
- app/views/users/show.html.erb
fix policies for profile editing. check please @pins-thoo @Katsulincon
> Update policy to not allow users to update other people's profile

- app/views/devise/registrations/edit.html.erb
check please @Katsulincon @pins-thoo
> Can now upload photo from user edit page

- app/assets/stylesheets/components/_footer.scss
- app/assets/stylesheets/components/_index.scss
- app/views/layouts/application.html.erb
- app/views/shared/_footer.html.erb
> Add footer

- app/assets/stylesheets/components/_footer.scss
- app/views/layouts/application.html.erb
> Made footer sticky to the bottom page
